language: common-lisp
sudo: false

addons:
  apt:
    packages:
    - zip

env:
  global:
  - GAMEKIT_SYSTEM_NAME: decent-game
  - GAMEKIT_APPLICATION_PACKAGE: decent-game
  - GAMEKIT_APPLICATION_MAIN_CLASS: decent-game
  - PATH: ~/bin/:$PATH
  - GAMEKIT_TARGET_PACKAGE: $GAMEKIT_SYSTEM_NAME-x86-64-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip
  - GAMEKIT_BUILD_DIR: /tmp/$GAMEKIT_SYSTEM_NAME
  - secure: "CILXscSAoBEFOlaPuo+3S5Kxl/+g1rDM3B5G5hJO42ig/JASwwid1InNpyLZQWS1C13nOJKpPXlvMn2SQ32zhKvx0dUCOWvKNVwzRG+mK+h8KpI1otKaHCWjPl0DPE6MbUsvdkYkjpyY0ULWx7CxCLgJ7qDnnBA41b99X/O0ikMEE5Ix10T3EHIpAPVlxH+FAnZoywOzx3gRP9+NJpDXx198nkUPM0ptS5Bv1QZiAYBECf3RmVhgvfddYyv1pfVISQTu4UDbCJuOZ/ZtE+BBq43l6JC1dQ733uG8SnR+Z10ISQexi62G8b8ir1J0Iw5NAKxUZBlKqks2NlnhK3JFdGOlDzxsG86H6gderm9IpOEq8E2gvHp5bp2zYyJSqxVA0hcfRi7PhCkckMrIJI+tfZMajx1OPERXlUUtjgFKD4M0VIxvjcguGUCjk99WrKEWfvA8KzshoGEJi2LSQ5VGNYG5JTHO8HzXvo2CXU3t5ylD18thJTZX3q2IKGGJXQsI5Z3n/F+Rj8767HftI6JBAXfIbuUbyj35BNyOZGXUbGuekPNVerNGKUXwo0uumN8agUiEa3IY44E+olHsceixc1MRvF3ogZH+IOaFHvtJvz2gBTfeoQ3F+/dRirymTEouuVohpCnf9IQw84KYKQpkM9olqramzgIQLqoU7KGeL68="

branches:
  only:
    - "/^v\\d+(\\.\\d+)+$/"

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git-lfs; fi
  - curl -L http://bodge.borodust.org/files/install.sh | sh
  - git lfs install && git lfs pull

script:
  - >
    lisp $HOME/bodge/scripts/build-experimental-gamekit-system.lisp
    $GAMEKIT_SYSTEM_NAME $GAMEKIT_APPLICATION_PACKAGE $GAMEKIT_APPLICATION_MAIN_CLASS
    $TRAVIS_BUILD_DIR
    $GAMEKIT_BUILD_DIR

before_deploy:
  - mv "$GAMEKIT_BUILD_DIR/$GAMEKIT_SYSTEM_NAME.zip" $GAMEKIT_TARGET_PACKAGE

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: $GAMEKIT_TARGET_PACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
